env:
  es6: true
  node: true
extends:
  - airbnb-base
  - plugin:import/typescript
  - "plugin:@typescript-eslint/recommended"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2020
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  no-new: 0
  import/prefer-default-export: 0
  import/extensions: 0
  "@typescript-eslint/no-non-null-assertion": 0
  no-new-func: 0
  "@typescript-eslint/explicit-module-boundary-types": 0
  no-console: 0
