name: pr-commitlint-action
description: A GitHub Action that checks Pull Request name with commitlint
  config, aiming to be consistent with commit names
runs:
  using: docker
  image: docker://vikuko/pr-commitlint-action:v0.1.8
inputs:
  config:
    description: Commitlint config file path
    default: commitlint.config.js
    required: false
  strict:
    description: Action will fail even if warnings are detected when in strict mode
    default: true
    required: false
  verbose:
    description: Whether commitlint output shoud be verbose when failing
    default: false
    required: false
branding:
  icon: check-square
  color: green
