name: Release

on:
  push:
    branches:
      - release

jobs:

  changelog:
    name: Generate Changelog
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.changelog.outputs.tag }}
      skipped: ${{ steps.changelog.outputs.skipped }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12

      - name: Install & Build
        run: npm install && npm run ci:build

      - name: Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-message: 'chore(release): bump to {version}'
          preset: conventionalcommits
          pre-commit: ci/dist/index.js
          skip-on-empty: false

  release:
    name: Release & Deploy
    runs-on: ubuntu-latest
    needs: changelog
    if: needs.changelog.outputs.skipped == 'false'
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12

      - name: Install & Build
        run: npm install && npm run build

      - name: Docker Release
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: vikuko/pr-commitlint-action
          path: dockerhub
          tags: ${{ needs.changelog.outputs.tag }}

      # - name: Github Release
      #   uses: actions/create-release@v1
      #   if: ${{ steps.changelog.outputs.skipped == 'false' }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ steps.changelog.outputs.tag }}
      #     release_name: ${{ steps.changelog.outputs.tag }}
      #     body: ${{ steps.changelog.outputs.clean_changelog }}

  sync:
    name: Sync master & release
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0
          ssh-key: ${{ secrets.SSH_KEY }}

      - name: Rebase
        run: git rebase origin/release

      - name: Push
        run: git push origin master
